apiVersion: apps/v1
kind: Deployment
metadata:
  name: mtls-test-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mtls-test-server
  template:
    metadata:
      labels:
        app: mtls-test-server
    spec:
      containers:
      - name: mtls-test-server
        image: attiss/mtls-test-server:latest
        ports:
        - containerPort: 8443
        imagePullPolicy: Always
        volumeMounts:
        - name: certs
          mountPath: "/opt/test-certs"
          readOnly: true
      volumes:
      - name: certs
        secret:
          secretName: certs
---
apiVersion: v1
kind: Service
metadata:
  name: mtls-test-server
spec:
  type: NodePort
  ports:
  - port: 8443
    targetPort: 8443
    protocol: TCP
    name: https
  selector:
    app: mtls-test-server
